// Real Leben in Deutschland test questions, curated sample across categories.
// Bilingual: German is the study target, English is the comprehension aid.

window.LID_QUESTIONS = [
  {
    id: 1, num: 7, category: "Grundrechte",
    q: "In Deutschland dürfen Menschen offen etwas gegen die Regierung sagen, weil …",
    qEn: "In Germany, people may openly say things against the government because …",
    options: [
      "hier Religionsfreiheit gilt.",
      "die Menschen Steuern zahlen.",
      "hier Meinungsfreiheit gilt.",
      "hier Schulpflicht besteht.",
    ],
    optionsEn: [
      "freedom of religion applies here.",
      "people pay taxes.",
      "freedom of opinion applies here.",
      "mandatory schooling exists here.",
    ],
    correct: 2,
    hint: "A core right: people can publicly criticise the government because freedom of opinion (Meinungsfreiheit) applies — not religion, not because of tax, not because of school.",
    keywords: [
      { de: "Meinungsfreiheit", en: "freedom of opinion" },
      { de: "Regierung", en: "government" },
    ],
  },
  {
    id: 2, num: 2, category: "Gesellschaft und Familie",
    q: "In Deutschland können Eltern bis zum 14. Lebensjahr ihres Kindes entscheiden, ob es in der Schule am …",
    qEn: "In Germany, parents can decide until their child is 14 whether it takes part at school in …",
    options: [
      "Geschichtsunterricht teilnimmt.",
      "Religionsunterricht teilnimmt.",
      "Politikunterricht teilnimmt.",
      "Sprachunterricht teilnimmt.",
    ],
    optionsEn: [
      "history class.",
      "religion class.",
      "politics class.",
      "language class.",
    ],
    correct: 1,
    hint: "Religion class is the optional one — parents decide until the child is 14. Everything else is mandatory.",
    keywords: [
      { de: "Religionsunterricht", en: "religious education class" },
      { de: "14. Lebensjahr", en: "14th year of life" },
    ],
  },
  {
    id: 3, num: 55, category: "Politik in der Demokratie",
    q: "Wie heißt die deutsche Verfassung?",
    qEn: "What is the German constitution called?",
    options: ["Volksgesetz", "Grundgesetz", "Bundesgesetz", "Deutsches Gesetz"],
    optionsEn: ["People's Law", "Basic Law", "Federal Law", "German Law"],
    correct: 1,
    hint: "Germany's constitution is called the Grundgesetz — literally 'basic law'. Written in 1949 in Bonn.",
    keywords: [
      { de: "Verfassung", en: "constitution" },
      { de: "Grundgesetz", en: "basic law (the constitution)" },
    ],
  },
  {
    id: 4, num: 130, category: "Politik in der Demokratie",
    q: "Wie viele Bundesländer hat die Bundesrepublik Deutschland?",
    qEn: "How many federal states does the Federal Republic of Germany have?",
    options: ["14", "15", "16", "17"],
    optionsEn: ["fourteen", "fifteen", "sixteen", "seventeen"],
    correct: 2,
    hint: "Sixteen federal states (Bundesländer). Easy mnemonic: 1+6 = 7, the same as the digit count in 'sechzehn'.",
    keywords: [
      { de: "Bundesländer", en: "federal states" },
      { de: "Bundesrepublik", en: "federal republic" },
    ],
  },
  {
    id: 5, num: 100, category: "Geschichte und Verantwortung",
    q: "Wann wurde die Bundesrepublik Deutschland gegründet?",
    qEn: "When was the Federal Republic of Germany founded?",
    options: ["1939", "1945", "1949", "1989"],
    optionsEn: ["start of WWII", "end of WWII", "post-war founding", "fall of the Wall"],
    correct: 2,
    hint: "Founded in 1949 — four years after the end of WWII. 1945 = end of war, 1989 = fall of the Wall, 1939 = start of war.",
    keywords: [
      { de: "gegründet", en: "founded" },
      { de: "Bundesrepublik", en: "federal republic" },
    ],
  },
  {
    id: 6, num: 78, category: "Politik in der Demokratie",
    q: "Wer wählt in Deutschland den Bundeskanzler / die Bundeskanzlerin?",
    qEn: "Who elects the federal chancellor in Germany?",
    options: ["das Volk", "die Bundesversammlung", "der Bundestag", "der Bundesrat"],
    optionsEn: ["the people", "the Federal Convention", "the federal parliament", "the Federal Council"],
    correct: 2,
    hint: "The Bundestag (parliament) elects the chancellor. The Bundesversammlung elects the president — easy to mix up.",
    keywords: [
      { de: "Bundeskanzler", en: "federal chancellor" },
      { de: "Bundestag", en: "federal parliament" },
    ],
  },
  {
    id: 7, num: 200, category: "Geographie",
    q: "Was ist die Hauptstadt der Bundesrepublik Deutschland?",
    qEn: "What is the capital of the Federal Republic of Germany?",
    options: ["Bonn", "München", "Hamburg", "Berlin"],
    optionsEn: ["Bonn (former West capital)", "Munich", "Hamburg", "Berlin"],
    correct: 3,
    hint: "Berlin since reunification in 1990. Bonn was the West German capital before that.",
    keywords: [{ de: "Hauptstadt", en: "capital city" }],
  },
  {
    id: 8, num: 45, category: "Rechtsstaat",
    q: "Welche Aufgabe hat ein Richter / eine Richterin in Deutschland?",
    qEn: "What is the role of a judge in Germany?",
    options: [
      "Er / Sie regiert das Land.",
      "Er / Sie schreibt die Gesetze.",
      "Er / Sie spricht Recht.",
      "Er / Sie macht Politik.",
    ],
    optionsEn: [
      "He / she governs the country.",
      "He / she writes the laws.",
      "He / she applies the law (judges cases).",
      "He / she does politics.",
    ],
    correct: 2,
    hint: "Judges apply the law — 'Recht sprechen' literally means 'to speak justice'. Parliament writes laws; government rules.",
    keywords: [
      { de: "Richter", en: "judge" },
      { de: "Recht sprechen", en: "to apply / pass judgement" },
    ],
  },
  {
    id: 9, num: 167, category: "Geschichte und Verantwortung",
    q: "Wann ist in Deutschland der „Tag der Deutschen Einheit\"?",
    qEn: "When is Germany's 'Day of German Unity'?",
    options: ["9. November", "8. Mai", "3. Oktober", "17. Juni"],
    optionsEn: ["9 November (fall of the Wall)", "8 May (V-E Day)", "3 October", "17 June"],
    correct: 2,
    hint: "October 3rd, 1990 — the day East and West Germany officially reunified. November 9th is a 'fateful day' but not the holiday.",
    keywords: [{ de: "Einheit", en: "unity / reunification" }],
  },
  {
    id: 10, num: 4, category: "Grundrechte",
    q: "Welches Recht gehört zu den Grundrechten in Deutschland?",
    qEn: "Which right is among the fundamental rights in Germany?",
    options: ["Waffenbesitz", "Faustrecht", "Meinungsfreiheit", "Selbstjustiz"],
    optionsEn: ["gun ownership", "rule of the fist (mob rule)", "freedom of opinion", "vigilante justice"],
    correct: 2,
    hint: "Freedom of opinion is a fundamental right. The other three describe lawlessness — guns, fist-law, vigilante justice.",
    keywords: [{ de: "Grundrechte", en: "fundamental rights" }],
  },
  {
    id: 11, num: 88, category: "Politik in der Demokratie",
    q: "Was bedeutet die Abkürzung „CDU\" in Deutschland?",
    qEn: "What does the abbreviation 'CDU' stand for in Germany?",
    options: [
      "Christlich-Deutsche Union",
      "Club Deutscher Unternehmer",
      "Christlich Demokratische Union",
      "Christliche Demokratische Unternehmer",
    ],
    optionsEn: [
      "Christian-German Union",
      "Club of German Entrepreneurs",
      "Christian Democratic Union",
      "Christian Democratic Entrepreneurs",
    ],
    correct: 2,
    hint: "Christlich Demokratische Union — the centre-right party. The 'U' is Union, not Unternehmer (entrepreneur).",
    keywords: [{ de: "Abkürzung", en: "abbreviation" }],
  },
  {
    id: 12, num: 112, category: "Rechtsstaat",
    q: "Was bedeutet „Rechtsstaat\" in Deutschland?",
    qEn: "What does 'Rechtsstaat' (constitutional state) mean in Germany?",
    options: [
      "Der Staat hat ein Rechtssystem.",
      "Der Staat muss sich an die Gesetze halten.",
      "Die Bürger denken rechts.",
      "Im Staat gibt es nur rechte Parteien.",
    ],
    optionsEn: [
      "The state has a legal system.",
      "The state must abide by its own laws.",
      "The citizens think right-wing.",
      "There are only right-wing parties in the state.",
    ],
    correct: 1,
    hint: "A Rechtsstaat = a state bound by its own laws. Even the government has to follow them. Nothing to do with 'right-wing' politics.",
    keywords: [
      { de: "Rechtsstaat", en: "state ruled by law" },
      { de: "sich halten an", en: "to abide by" },
    ],
  },
  {
    id: 13, num: 220, category: "Geschichte und Verantwortung",
    q: "Was geschah am 9. November 1989 in Deutschland?",
    qEn: "What happened on 9 November 1989 in Germany?",
    options: [
      "Die Bundesrepublik wurde gegründet.",
      "Die DDR wurde gegründet.",
      "Die Berliner Mauer öffnete sich.",
      "Deutschland wurde wiedervereinigt.",
    ],
    optionsEn: [
      "The Federal Republic was founded.",
      "The GDR (East Germany) was founded.",
      "The Berlin Wall opened.",
      "Germany was reunified.",
    ],
    correct: 2,
    hint: "The Wall fell on 9 November 1989. Formal reunification came almost a year later on 3 October 1990.",
    keywords: [
      { de: "Berliner Mauer", en: "Berlin Wall" },
      { de: "wiedervereinigt", en: "reunified" },
    ],
  },
  {
    id: 14, num: 19, category: "Gesellschaft und Familie",
    q: "Welche Aussage ist richtig? In Deutschland …",
    qEn: "Which statement is correct? In Germany …",
    options: [
      "gibt es keine Religionsfreiheit.",
      "dürfen nur Christen ihre Religion ausüben.",
      "können die Menschen ihre Religion frei wählen.",
      "müssen alle an Gott glauben.",
    ],
    optionsEn: [
      "there is no freedom of religion.",
      "only Christians may practice their religion.",
      "people may freely choose their religion.",
      "everyone must believe in God.",
    ],
    correct: 2,
    hint: "Religionsfreiheit is constitutional. People may freely choose their religion — or none at all.",
    keywords: [{ de: "Religionsfreiheit", en: "freedom of religion" }],
  },
  {
    id: 15, num: 145, category: "Politik in der Demokratie",
    q: "Wie heißt Deutschlands heutige Staatsform?",
    qEn: "What is Germany's current form of government?",
    options: [
      "Parlamentarische Demokratie",
      "Konstitutionelle Monarchie",
      "Sozialistische Republik",
      "Direkte Demokratie",
    ],
    optionsEn: [
      "parliamentary democracy",
      "constitutional monarchy",
      "socialist republic",
      "direct democracy",
    ],
    correct: 0,
    hint: "A parliamentary democracy: the parliament (Bundestag) holds central power and elects the chancellor.",
    keywords: [
      { de: "Staatsform", en: "form of government" },
      { de: "parlamentarisch", en: "parliamentary" },
    ],
  },
  {
    id: 16, num: 60, category: "Grundrechte",
    q: "Welches Grundrecht haben alle Menschen in Deutschland?",
    qEn: "Which fundamental right do all people in Germany have?",
    options: [
      "Sie können in Deutschland Auto fahren.",
      "Sie können sich frei versammeln.",
      "Sie können Soldat / Soldatin werden.",
      "Sie können wählen gehen.",
    ],
    optionsEn: [
      "They can drive a car in Germany.",
      "They can freely assemble.",
      "They can become a soldier.",
      "They can vote.",
    ],
    correct: 1,
    hint: "Versammlungsfreiheit — the right to peaceful assembly — applies to everyone. Voting and military service are tied to citizenship.",
    keywords: [{ de: "sich versammeln", en: "to assemble / gather" }],
  },
  {
    id: 17, num: 270, category: "Geschichte und Verantwortung",
    q: "Wann fanden die ersten freien Wahlen in der DDR statt?",
    qEn: "When did the first free elections in the GDR (East Germany) take place?",
    options: ["1953", "1961", "1989", "1990"],
    optionsEn: ["uprising of 1953", "Wall built", "Wall fell", "first free election"],
    correct: 3,
    hint: "March 1990 — the first and only free Volkskammer election, six months before reunification.",
    keywords: [
      { de: "freie Wahlen", en: "free elections" },
      { de: "DDR", en: "East Germany (GDR)" },
    ],
  },
  {
    id: 18, num: 33, category: "Politik in der Demokratie",
    q: "Wahlen in Deutschland sind …",
    qEn: "Elections in Germany are …",
    options: [
      "frei, geheim, gleich.",
      "freiwillig und geheim.",
      "geheim und unkontrolliert.",
      "öffentlich und gleich.",
    ],
    optionsEn: [
      "free, secret, equal.",
      "voluntary and secret.",
      "secret and unchecked.",
      "public and equal.",
    ],
    correct: 0,
    hint: "Five principles: allgemein, unmittelbar, frei, gleich, geheim. The right answer combines three of them.",
    keywords: [
      { de: "geheim", en: "secret" },
      { de: "Wahl", en: "election" },
    ],
  },
];

window.LID_CATEGORIES = [
  "Alle Kategorien",
  "Grundrechte",
  "Politik in der Demokratie",
  "Geschichte und Verantwortung",
  "Gesellschaft und Familie",
  "Rechtsstaat",
  "Geographie",
];

window.LID_CATEGORIES_EN = {
  "Alle Kategorien": "all categories",
  "Grundrechte": "fundamental rights",
  "Politik in der Demokratie": "politics & democracy",
  "Geschichte und Verantwortung": "history & responsibility",
  "Gesellschaft und Familie": "society & family",
  "Rechtsstaat": "rule of law",
  "Geographie": "geography",
};
